### ISSUE TITLE
Generate does not work with node v18.16.0 or lower

### ISSUE THREAD

**Issue by jason-yang** [oclif/oclif#1632] opened 2024-12-11 00:47 UTC
**Is this a bug with the oclif CLI? Or the oclif framework?**

If it's an issue with the oclif framework please make the issue over at [@ocilf/core](https://github.com/oclif/core/)

**Describe the bug**

**To Reproduce**

1. Install node v18.15.0, e.g. `nvm install v18.15.0`
2. Install oclif: `npm i --global oclif`
3. Generate CLI: `oclif generate test --yes`
4. Error, and CLI not generated

```
> nvm use v18.15.0
Now using node v18.15.0 (npm v9.5.0)
> `npm i --global oclif`
.... output
> oclif generate test --yes
Generating test in /home/jyang/code/test
? Select a module type ESM
? NPM package name test
? Command bin name the CLI will export test
? Description A new CLI generated with oclif
? Author Jason Yang
? License MIT
? Who is the GitHub owner of repository (https://github.com/OWNER/repo) code
? What is the GitHub name of repository (https://github.com/owner/REPO) test
? Select a package manager npm
    TypeError: Cannot read properties of undefined (reading 'replace')
```

**Expected behavior**
CLI should generate without errors

**Your Environment (please complete the following information):**

- `oclif` Version [e.g. 4.5.0] 4.16.2
- OS & version: [e.g. MacOS Monterey, Ubuntu 20.04.4 LTS, Windows 10] Windows 10 + WSL 2 (Ubuntu 22.04.5 LTS)
- Shell/terminal & version [e.g. bash-3.2, bash-5.0, zsh 5.8, powershell 7.2.4, cmd.exe, Windows Terminal w/ powershell, etc... ] zsh-5.8.1

**Additional context**
Node <18.17.0 does not work, it works thereafter

**Comment by mdonnalley** [comment] 2024-12-11 15:54
This is duplicate of https://github.com/oclif/oclif/issues/1436

The solution is to use 18.20.3 or greater

**Closed by mdonnalley** 2024-12-11 15:54 UTC
