### ISSUE TITLE
Can't extend base class with subclass with other flags

### ISSUE THREAD

**Issue by BravoNatalie** [oclif/oclif#1025] opened 2022-11-09 15:47 UTC
I have the following base class:

```
export class HealthCheck extends Command {
  static flags = {
    healthCheck: Flags.boolean({
      description: 'Launch server on http://localhost:6000 to make sure command is still running',
      default: false,
    }),
    healthCheckPort: Flags.integer({
      description: 'This flag allows you to choose what port the health check sever is running on.',
      default: 6000,
      dependsOn: ['healthCheck'],
    }),
  }

  async run(): Promise<void> {
    const {flags} = await this.parse(HealthCheck)

    const enableHealthCheckServer = flags.healthCheck
    const healthCheckPort = flags.healthCheckPort

    if (enableHealthCheckServer && !portValidator(healthCheckPort)) {
      this.error('The port should be in the [3000, 65535] range.')
    }
  }
}
```

The following abstract class extends the base class:
```
export abstract class OperatorJobAwareCommand extends HealthCheck { ... }
```

And another class that extends the `OperatorJobAwareCommand`:

```
export default class Operator extends OperatorJobAwareCommand {
  ...
  static flags = {
    mode: Flags.string({
      description: 'The mode in which to run the operator',
      options: Object.values(OperatorMode),
      char: 'm',
    }),
    ...HealthCheck.flags,
  }
  
  async run(): Promise<void> {
    await super.run()
    const {flags} = await this.parse(Operator)
    ...
    }
 }
```

What is the current behavior?
-----------------------------
When I try to run the command operator with the flags defined in the Operator I have the following error:

![image](https://user-images.githubusercontent.com/37748828/200875929-6791f7c4-ea7a-4a68-8ed6-e7868c07cd34.png)

What is the expected behavior?
------------------------------
I should run without any problems.

**Comment by mdonnalley** [comment] 2022-11-09 16:09
@BravoNatalie Try changing `HealthCheck.flags` to `HealthCheck.globalFlags`. 

```typescript
export class HealthCheck extends Command {
  static globalFlags = {
    healthCheck: Flags.boolean({
      description: 'Launch server on http://localhost:6000 to make sure command is still running',
      default: false,
    }),
    healthCheckPort: Flags.integer({
      description: 'This flag allows you to choose what port the health check sever is running on.',
      default: 6000,
      dependsOn: ['healthCheck'],
    }),
  }
}
```

See the docs about defining global flags: https://oclif.io/docs/global_flags

(As a side note, global flags is a misleading name for what they are. It's really "inheritable flags", i.e. flags that are defined in a base class and will be inherited by any class that extends it.)

**Comment by BravoNatalie** [comment] 2022-11-09 16:17
@mdonnalley It still does not work.

It seems that the base class is reverting because the others flags are not defined in there.

**Comment by mdonnalley** [comment] 2022-11-09 16:28
@BravoNatalie Can you elaborate on what you mean by "the base class is reverting"?

Also, have seen the [docs on using base classes](https://oclif.io/docs/base_class)? It gives a working example of how to implement base classes.

Finally, guessing by the code you've given me it looks like you intend to have separate `health check` and `operator` commands but you want the `operator` command to always run the `health check` command first. If that's the case you could avoid inheritance altogether by using `this.config.runCommand`. For example:

```typescript
export default class Operator extends Command {
  ...
  static flags = {
    mode: Flags.string({
      description: 'The mode in which to run the operator',
      options: Object.values(OperatorMode),
      char: 'm',
    }),
    ...HealthCheck.flags,
  }
  
  async run(): Promise<void> {
    const {flags} = await this.parse(Operator)
    await this.config.runCommand(`health:check`, ['--healthCheck', flags.healthCheck, `--healthCheckPort`, flags.healthCheckPort])
    ...
    }
 }
```

**Comment by BravoNatalie** [comment] 2022-11-09 16:48
@mdonnalley When I say that it's reverting I mean that whenever I try to use the flags of the operator I receive the error above.

You can ignore the HealthCheck class name since the idea is to be able to add more global flags to it, so in the end, it should work as a BaseClass. I already did this implementation before and it worked, but for some reason, it's not working now. I also implemented it in the same way as the docs and it still didn't work.

**Comment by mdonnalley** [comment] 2022-11-09 16:58
@BravoNatalie I think the problem is the way that you're calling `this.parse` in the base class

`const {flags} = await this.parse(HealthCheck)`

This is going to parse the flags based on the flags defined in `HealthCheck` not the flags in `Operator`. The `mode` flag isn't defined in `HealthCheck` so it's throwing the `Unexpected arguments` error.

If you look at the example base class in the docs it does the parse inside the `init` method and passes `this.constructor` into it

```typescript
  public async init(): Promise<void> {
    await super.init()
    const {flags} = await this.parse(this.constructor as Interfaces.Command.Class)
    this.flags = flags
  }
```

This allows the `parse` method to parse the flags based on the child class instead of the base class. 

Does that help? If not, I will need you to create new repository that replicates the issue so that I can investigate further

**Comment by mdonnalley** [comment] 2022-11-09 17:32
@BravoNatalie Looks like it's failing validation because you have both a `default` and a `dependsOn` for the health check flags
```typescript
  static flags = {
    healthCheck: Flags.boolean({
      description: 'Launch server on http://localhost:6000 to make sure command is still running',
      default: false,
    }),
    healthCheckPort: Flags.integer({
      description: 'This flag allows you to choose what port the health check sever is running on.',
      default: 6000,
      dependsOn: ['healthCheck'],
    }),
```

With `dependsOn` you're saying "the `healthCheck` flag should always be present if `healthCheckPort` is used". Or put another way, "the `healthCheckPort` flag cannot have a value unless `healthCheck` also has a value". 

But `healthCheckPort` will always have a value since it has a `default`. So the validation fails since `healthCheckPort` has a value but `healthCheck` doesn't also have a truthy value (`default: false` is falsy).

**Comment by BravoNatalie** [comment] 2022-11-09 17:42
But isn't this behavior a bug? Shouldn't the parser enforce this behavior unless I'm actually providing a value?

**Comment by mdonnalley** [comment] 2022-11-09 17:48
@BravoNatalie This is working as designed. The parser is failing because you've specified that `healthCheckPort` cannot exist if `healthCheck` doesn't also exist. Giving `healthCheckPort` a truthy default and `healthCheck` a falsy default, means that `healthCheckPort` exists when `healthCheck` doesn't exist - thus causing the error. 

The simple solution is to either remove the `default` or the `dependsOn` from the `healthCheckPort` flag

**Closed by mdonnalley** 2022-11-09 17:48 UTC
