### ISSUE TITLE
Add a generator command to add oclif to an existing project

### ISSUE THREAD

**Issue by joshcanhelp** [oclif/oclif#1355] opened 2024-04-03 19:31 UTC
**Is your feature request related to a problem? Please describe.**
There is no way to add oclif to an existing project and the [getting started docs](https://oclif.io/docs/introduction) only show commands for generating a new CLI. I had to sort of reverse engineer what the `oclif generate NAME` creates in order to figure out what's required.

**Describe the solution you'd like**
It would be great to either have an option for `oclif generate` or a new command like `oclif init` or something that adds the foundational files and config required. It looks like it would need to:

- Add the `./bin/*` files
- Add the following to `package.json`:

```js
{
	// ...
	"oclif": {
		"commands": "./dist/commands"
	}
}
```

**Describe alternatives you've considered**
Documentation for this use case would suffice as well. 

**Additional context**
Happy to help with a PR here if you like the idea!

**Comment by mdonnalley** [comment] 2024-04-03 19:55
I'm going to close this since it's a duplicate of https://github.com/oclif/oclif/issues/999

Would happily take a PR if you're up to the task. I like the idea of an `oclif init` command over having an option on `oclif generate`

**Closed by mdonnalley** 2024-04-03 19:55 UTC
