### ISSUE TITLE
Duplicate flag "char"s should be detected

### ISSUE THREAD

**Issue by spaghetti-is-pasta** [oclif/oclif#264] opened 2019-07-12 21:55 UTC
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
bug

What is the current behavior?
-----------------------------
You can define multiple flags with the same "char".

What is the expected behavior?
------------------------------
This should fail with a nice error.

**Comment by RasPhilCo** [comment] 2019-07-16 18:49
It likely should, or caught by a (in-progress) oclif linter.

**Comment by moulikcipherX** [comment] 2019-07-19 17:09
Hy @RasPhilCo where is actually multiple flags generated?

**Comment by RasPhilCo** [comment] 2019-07-19 19:41
@moulikcipherX this should throw a linter error

```
static flags = {
  name: flags.string({char: 'f'}),
  number: flags.string({char: 'f'}),
}
```

**Comment by moulikcipherX** [comment] 2019-07-19 20:11
I hope this bug is generated when we create cli using oclif.

**Comment by moulikcipherX** [comment] 2019-07-19 20:23
@RasPhilCo working on it. This is again in the under src/commands/ classes.

**Comment by moulikcipherX** [comment] 2019-07-20 22:39
Hy @RasPhilCo successfully created the rule and committed to the new branch **new-rule** in eslint

**Closed** 2022-08-16 16:34 UTC

**Comment by 0xdevalias** [comment] 2022-08-17 02:09
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
