### ISSUE TITLE
[Bug] `oclif pack tarball` doesn't work with pnpm

### ISSUE THREAD

**Issue by DominicGBauer** [oclif/oclif#1245] opened 2024-01-11 14:12 UTC
*bug*?
-----------------------------------------------------

What is the current behavior?
-----------------------------
Run `oclif pack tarballs` in `pnpm` project 

```
oclif: gathering workspace for powersync to /Users/dominic/Desktop/power-sync/cli/tmp/powersync
    Error: Command failed: yarn -v
    No preset version installed for command yarn
```

What is the expected behavior?
------------------------------
I shouldn't need to use yarn to run commands

**Comment by mdonnalley** [comment] 2024-01-11 15:52
Thanks for the issue @DominicGBauer - I'm going to close since it's a duplicate of https://github.com/oclif/oclif/issues/1219

Feel free to post any ideas or insights to that issue

**Closed by mdonnalley** 2024-01-11 15:52 UTC
