### ISSUE TITLE
feat: dynamic target

### ISSUE THREAD

**Issue by jjangga0214** [oclif/oclif#1544] opened 2024-09-12 03:58 UTC
**Is your feature request related to a problem? Please describe.**

Currently, `oclif.commands` has a single value. 

*`package.json`*:

```json
{
  "oclif": {
    "commands": "./dist/commands"
  }
}
```

Therefore, I have to compile typescript into *`dist`* to `./bin/dev.js <command>`.
I want it to be dynamic, depending on whether its runtime environment is dev or not.

**Describe the solution you'd like**

*`package.json`*:

```json
{
  "oclif": {
    "commands": {
      "dev": "./src/commands",
      "run": "./dist/commands"
    }
  }
}
```

So, `./bin/dev.js <command>` will find command from *`./src/commands`*, 
while `./bin/run.js <command>` from *`./dist/commands`*.

So in the development environment, we can skip the manual build process, and make use of `ts-node` directly.

Thanks,

**Comment by mdonnalley** [comment] 2024-09-12 15:28
duplicate of https://github.com/oclif/oclif/issues/1543

**Closed by mdonnalley** 2024-09-12 15:28 UTC
