### ISSUE TITLE
Document the 'env' option of a flag in the help

### ISSUE THREAD

**Issue by sgarciac** [oclif/oclif#1536] opened 2024-09-06 13:53 UTC
When the option 'env' is used for a flag, it is currently not documented in the command's help. The user has no way to know it can use an env var as a default value for the flag.

**Comment by mdonnalley** [comment] 2024-09-06 14:54
duplicate of https://github.com/oclif/core/issues/981

**Closed by mdonnalley** 2024-09-06 14:54 UTC
