### ISSUE TITLE
Command with arguments and multiple value flag

### ISSUE THREAD

**Issue by ernieturner** [oclif/oclif#190] opened 2018-11-20 19:48 UTC
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

More of a confirmation that what I'm trying to do isn't supported.

What is the current behavior?
-----------------------------

I have a command that takes an argument but also has a flag that takes multiple values. However, it doesn't look like the combination is supported, unless I'm missing something. If my flag takes multiple values, it doesn't know when to stop parsing the flag values and when to start parsing arguments. For example if I setup my command like so

```
static args = [{name: "file", required: true}];
static flags = {
  mod: flags.string({
    char: 'm',
    multiple: true
  })
};
```

Then there isn't a way to provide values for the `-m` flag as well as an argument because parsing the `-m` flag doesn't know when to stop parsing flag arguments and when to start parsing command arguments. For example, `command -m one two file.txt` would end in an error because it won't see any arguments to the command and creates a `flags.mod` array of `["one", "two", "file.txt"]`.

What is the expected behavior?
------------------------------

It seems like the only way to really support this would be some way to configure oclif to allow flags to be specified multiple times, but _only with one value per flag_. In my above example it would be something like `command -m one -m two file.txt`. Is there anyway to setup a command like that currently?

**Comment by jdxcode** [comment] 2018-11-20 23:09
I think this might be a duplicate of https://github.com/oclif/oclif/issues/190

**Comment by ernieturner** [comment] 2018-11-21 05:17
I did see that ticket, but I didn't really understand what was being asked there, if it was similar to my issue or if it was just TypeScript confusion. So to confirm, I'm correct in that what I'm trying to do isn't something that is supported?

**Comment by ytilis** [comment] 2018-12-18 23:44
I'm pretty sure #184 is just confusion on how to use the `multiple` attribute on a flag. The issue here seems to be flag parsing itself not differentiating arguments from additional flags if you try to pass an argument *after* you start calling flags.

@ernieturner have you tried flipping the order you pass the flags and arguments? 
In other words, instead of doing 
```
command -m one two file.txt
```

try calling it as
```
command file.txt -m one two
```

I just tried it and it seems to work for me.

**Comment by ernieturner** [comment] 2018-12-18 23:56
@ytilis Yep, I've tried that and I know that if you get the order correct it works, but it's not something I can really expect all my users to do correctly. Most CLI tools have the expectation that you can provide the flags at any point in the command and they don't have to come last so I was hoping there was a way to keep that expectation.

**Comment by nevir** [comment] 2019-04-24 21:55
This was a huge surprise for me as well, most CLI tools seem pretty consistent in expressing flags as pairs, rather than variadic lists.

E.g. for multiple-use flags, you'd expect to pass the flag each time:
```
command -m one -m two file.txt
```
Rather than
```
command file.txt -m one -m two
```

---

It's interesting to note that oclif/parser seems to parse flags this way internally (looking at `raw`, the flag values _are_ pairwise)

**Comment by jdxcode** [comment] 2019-04-24 22:47
@nevir `command -m one -m two` is how oclif works

**Comment by nevir** [comment] 2019-04-25 00:17
Given this command:

```ts
class Testcmd extends Command {
  static flags = {
    mod: flags.string({
      char: 'm',
      multiple: true
    })
  };
  static args = [{name: 'file'}]

  async run() {
    console.log(this.parse(Testcmd));
  }
}
```

---

If I run: `command  -m one two`, it parses into:
```
{ args: { file: undefined }, flags: { mod: [ 'one', 'two' ] } }
```
👎 expected instead:
```
{ args: { file: 'two' }, flags: { mod: [ 'one' ] } }
```

---

If I run: `command zero -m one -m two`, it parses into:
```
{ args: { file: 'zero' }, flags: { mod: [ 'one', 'two' ] } }
```
👍 matches expectation

---

If I run: `command zero -m one -m two three` (with `strict = false`), it parses into:
```
{ argv: [ 'zero' ], flags: { mod: [ 'one', 'two', 'three' ] } }
```
👎 expected instead:
```
{ argv: [ 'zero', 'three' ], flags: { mod: [ 'one', 'two' ] } }
```

**Comment by jdxcode** [comment] 2019-04-25 00:49
That’s surprising. I’m pretty certain this is a bug then

**Comment by jdxcode** [comment] 2019-04-25 03:24
ok, I completely forgot about this [PR that added this behavior](https://github.com/oclif/parser/pull/25). I think at the time I didn't consider how this might conflict with args but clearly it does. I'm chatting with @RasPhilCo about it and what we should do. My initial thought is this is the wrong behavior even though it makes it work well with filenames and `*` like shown in the PR.

**Comment by nevir** [comment] 2019-04-25 15:49
Aha! Yeah, might be worth making it an option for flags, but that behavior is pretty surprising as a default behavior

**Comment by alexturek** [comment] 2020-03-24 21:49
Hey just checking to see if this is on anyone's radar. [This comment](https://github.com/oclif/oclif/issues/190#issuecomment-486506080) makes it look like the fix is probably straightforward, and I see that the last (open source) thing to reference this issue got closed... after they switched away from oclif.

**Comment by mjgp2** [comment] 2020-04-10 12:37
I am wondering the same thing because this is an issue for me - are PRs still actively being considered or is the project without a maintainer if Salesforce have ditched it?

**Comment by srlowe** [comment] 2020-06-26 10:39
Also very interested in the status of this.  Are community contributions towards fixing this acceptable to the maintainers?

**Comment by jwenjian** [comment] 2020-07-05 09:34
subscribe to this issue, I also faced same question, when my flags `-t` is multiple and my arg `text` is required, below command :

```
./bin/run new -t one -t two "test text"

```

give me an error:

```
 ›   Error: Missing 1 required arg:
 ›   text  text to giki
```
I have to put the multiple flag `-t` after the arg `text` to make it work:

```
./bin/run new "test text" -t one -t two
```

**Comment by RasPhilCo** [comment] 2020-07-06 22:25
From https://github.com/oclif/parser/pull/79#issuecomment-653191584

> @cxam thanks for the PR! `$ cli foo -a foo bar` shouldn't pass bar as a flag. I want to revert that PR's behavior. I'll put this on our project board for looking at next.

**Comment by Jokero** [comment] 2020-10-12 17:16
@RasPhilCo Are there any updates? I was also wondered when noticed the behaviour described in the issue

**Comment by tjhiggins** [comment] 2021-08-16 18:00
Posting our workaround that doesn't require modifying oclif code or waiting for the pr to be merged. 
Creates a base command class that extends the parse method to move all args to the front. This avoids the weird parsing behavior for multi-flags. It also enforces one value per flag.

```ts
import Command, { flags } from '@oclif/command';

export default abstract class extends Command {
  // Move all args to the front of the argv to get around: https://github.com/oclif/oclif/issues/190
  parse(options: any, argv = this.argv): any {
    const flagDefinitions = (this.constructor as any).flags;

    const args = [];
    const flags = [];
    let isFlagOption = false;
    for (const arg of argv) {
      const isFlag = arg.startsWith('-');

      if (isFlag || isFlagOption) {
        flags.push(arg);
      } else {
        args.push(arg);
      }

      if (isFlag) {
        const flagDefinition = arg.startsWith('--') ? flagDefinitions[arg.replace('--', '')] : Object.values(flagDefinitions).find((f: any) => f.char === arg.replace('-', ''));
        isFlagOption = flagDefinition?.type === 'option';
      } else {
        isFlagOption = false;
      }
    }

    return super.parse(options, [...args, ...flags]);
  }
}
```

Usage:
```ts
import Command from '../base-command';

export default class MyCommand extends Command {
  ...
}
```

**Comment by wjramos** [comment] 2022-04-14 21:44
> ok, I completely forgot about this [PR that added this behavior](https://github.com/oclif/parser/pull/25). I think at the time I didn't consider how this might conflict with args but clearly it does. I'm chatting with @RasPhilCo about it and what we should do. My initial thought is this is the wrong behavior even though it makes it work well with filenames and `*` like shown in the PR.

One issue is that you cannot include flags following `--`

**Closed** 2022-08-16 16:46 UTC

**Comment by 0xdevalias** [comment] 2022-08-17 02:18
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.
