### ISSUE TITLE
Generate only shows a flickering snowstorm

### ISSUE THREAD

**Issue by mhvelplund** [oclif/oclif#788] opened 2022-01-09 10:47 UTC
Bug
----

What is the current behavior?
-----------------------------
When running `npx oclif generate` with any of the 2.0+ versions or `npx oclif@1.18.0 single`, the terminal is filled with a scrolling "snowstorm" of random looking characters. Nothing is generated.

Tested with every version of oclif from v1.18 and up, in WSL2/Ubuntu on Windows 10.

What is the expected behavior?
------------------------------
I expected the command to generate a project template :)

**Comment by mhvelplund** [comment] 2022-01-09 10:48
![example](https://user-images.githubusercontent.com/10400769/148679012-591c5d1e-b438-49bc-a8ec-c363c8dbb0ac.png)

**Comment by mdonnalley** [comment] 2022-01-10 04:37
Duplicate of https://github.com/oclif/oclif/issues/786

**Closed by mdonnalley** 2022-01-10 04:37 UTC
