### ISSUE TITLE
Dynamic commands stop working with oclif 2 run binaries

### ISSUE THREAD

**Issue by charan678** [oclif/oclif#942] opened 2022-08-26 12:37 UTC
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
I am trying to migrate project from oclif to oclif/core. I am following steps mentioned in this [migration document](https://github.com/oclif/core/blob/main/MIGRATION.md). After implementation of [Update your bin scripts](https://github.com/oclif/core/blob/main/MIGRATION.md#update-your-bin-scripts) step, existing [dynamic commands](https://github.com/oclif/oclif/issues/110) stopped working. 
I have implemented dynamic commands similar to this [example](https://github.com/jdxcode/oclif-example-dynamic-commands)
and also this project also showed same result where mydynamiccommand command stopped showing up after replacing run binary file and adding core dependency.

What is the expected behavior?
------------------------------
oclif core should support dynamic commands similar it does for oclif commands.

**Comment by mdonnalley** [comment] 2022-09-16 16:47
Duplicate of https://github.com/oclif/core/issues/479

**Closed by mdonnalley** 2022-09-16 16:47 UTC

**Comment by DanHulton** [comment] 2023-04-26 04:47
Anyone who comes across this, I think I have the answer for dynamic commands in oclif 2 posted over in the issue that this is a duplicate of: https://github.com/oclif/core/issues/479#issuecomment-1522774928

**Comment by DanHulton** [comment] 2023-05-07 21:38
Follow-up to my last comment, I packaged up the code for running dynamic commands into a plugin: [oclif-dynamic-commands on npm](https://www.npmjs.com/package/oclif-dynamic-commands).
