### ISSUE TITLE
Leaving repository owner and name empty breaks updating readme file

### ISSUE THREAD

**Issue by blikblum** [oclif/oclif#554] opened 2021-04-18 22:21 UTC
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

Bug

What is the current behavior?
-----------------------------

- Run the cli
- Leave Github repository owner empty (delete default value)
- Leave Github repository name empty (delete default value)
 
At end of installation an error will occur:
```
replacing <!-- usage --> in README.md
 »   Error: Invalid URL: /
``` 
The same error as above will occur when running `oclif command xxx`

Probably due to malformed url in package (repository, bugs and homepage):
```
{
  "bugs": "https://github.com///issues",
  "homepage": "https://github.com//",
  "repository": "/",
}
```

BTW: the app i'm developing is not hosted in github so i removed owner and name

What is the expected behavior?
------------------------------
Readme should be updated when at start and when running command

Oclif 1.7
Windows 10

**Comment by micapam** [comment] 2022-03-02 00:14
I also noticed this when I _did_ fill in the repo name. I think it was failing to strip whitespace from the end of the input. I typed in `epic-formulae ` (note trailing space) and the `bugs` entry in `package.json` ended up as `https://github.com/micapam/epic-formulae /issues` (note space character in the middle of URL).

**Comment by mdonnalley** [comment] 2024-03-01 19:26
Closing this since I'm not able to reproduce the original issue - please feel free to open a new issue if you're still experiencing this.

Created #1310 for the issue reported by @micapam

**Closed by mdonnalley** 2024-03-01 19:26 UTC
