### ISSUE TITLE
fatal: Too many arguments.

### ISSUE THREAD

**Issue by sauravraw** [oclif/oclif#784] opened 2022-01-06 05:03 UTC
What is the current behavior?
-----------------------------
By provided [link](https://www.npmjs.com/package/oclif/v/2.1.0#-usage) I tried to make a cli but I am getting this statement

![Screenshot from 2022-01-05 22-08-25](https://user-images.githubusercontent.com/73871061/148330702-606cd727-9aae-434e-ad99-d5812917397e.png)

so any reason why I am causing this warning or error?

Please mention your oclif and OS version?
-----------------------------
My OS is Ubuntu 20.04 with npm 7.19.1 and node v16.5.0

**Comment by mdonnalley** [comment] 2022-01-06 13:26
@sauravraw what version of git do you have?

**Comment by sauravraw** [comment] 2022-01-06 13:28
@mdonnalley git 2.34.1 previous 2.25

**Comment by mdonnalley** [comment] 2022-01-06 21:25
@sauravraw Based on the error message, my assumption is that it's failing on this `git clone` here: https://github.com/oclif/oclif/blob/main/src/generators/cli.ts#L74

Can you confirm that you're able to successfully run this:

```
git clone https://github.com/oclif/hello-world.git migrations
```

If that fails, we can assume that the issue is related to your installation of git

**Comment by sauravraw** [comment] 2022-01-07 02:53
@mdonnalley, Yes I can successfully clone given git command

`git clone https://github.com/oclif/hello-world.git migrations`

![Screenshot from 2022-01-07 08-22-21](https://user-images.githubusercontent.com/73871061/148483800-a0de5138-51df-45fc-81fe-1ac1ede9c622.png)

**Comment by sauravraw** [comment] 2022-01-07 11:22
Hi @mdonnalley, 

I downgrade from `oclif v2.1.0` to `oclif v1.18.4`. 
Now I can use `npx oclif multi migration` command to create package 
But when I am upgrading to `oclif v2.1.0` I am getting same fatal msg

![Screenshot from 2022-01-05 22-08-25](https://user-images.githubusercontent.com/73871061/148536405-a88647c1-7a3d-4b45-bc21-a328013b8dc6.png)

so is there any problem with the `v2.1.0` ?

System Specification 
OS: `Ubuntu 20.04`

Node - `v16.13.1`
NPM - `v8.3.0`
Git - `v2.34.1`

**Comment by sauravraw** [comment] 2022-01-10 07:59
Hi @mdonnalley, @RodEsp 
Any update regarding to this issue?

**Comment by mdonnalley** [comment] 2022-01-10 15:44
Fixed by https://github.com/oclif/oclif/pull/783

**Closed by mdonnalley** 2022-01-10 15:44 UTC
