### ISSUE TITLE
package manager selection throws error

### ISSUE THREAD

**Issue by YewTreeWeb** [oclif/oclif#1434] opened 2024-06-04 18:39 UTC
When I run the command pnpm dlx or npx oclif generate {name} and select a package manager I get the error `TypeError: Cannot read properties of undefined (reading 'replace')`. This then exits the setup and leaves me unable to install Oclif. I also have this error when installing oclif with `npm install --global oclif` I've have tried this with nom and pnpm. My pnpm install is with Brew and currently running 9.1.4.

**Comment by mdonnalley** [comment] 2024-06-04 18:52
@YewTreeWeb I'm not able to reproduce this on latest. What version of oclif are you using? Also, does the error happen while trying to select the package manager or does the error happen when oclif is trying to install the generated CLI's deps using the selected package manager?

**Comment by YewTreeWeb** [comment] 2024-06-04 18:58
Hi @mdonnalley, thanks for the quick reply. Npx and nom give me the version `oclif@4.12.4`. The error occurs when oclif gives the option to select a package manager and upon selection e.g. npm or pnpm I then get the error.
<img width="599" alt="Screenshot 2024-06-04 at 19 55 19" src="https://github.com/oclif/oclif/assets/18143654/72795579-5ea5-451e-b30d-8d11d1a55c35">

**Comment by mdonnalley** [comment] 2024-06-04 19:07
What version of node are you using?

**Comment by YewTreeWeb** [comment] 2024-06-04 19:53
I'm using v19.3.0

**Comment by mdonnalley** [comment] 2024-06-04 20:05
@YewTreeWeb Thanks, I was able to replicate with node 19.3.0

It doesn't fail if you downgrade to node 18 and it works if you upgrade to node 20. So I'm inclined to say that this is an issue with node 19, which is now unsupported: https://nodejs.org/en/about/previous-releases

Because of that, I'm going to close this issue. Happy to keep the conversation going though if you have any more questions/concerns.

**Closed by mdonnalley** 2024-06-04 20:05 UTC
Labels: needs more info

**Comment by YewTreeWeb** [comment] 2024-06-04 20:54
Thanks @mdonnalley appreciate all the help this seems to now work with npm. Kicking myself that I didn't think to check my Node version
