### ISSUE TITLE
Thrown error is malformatted with newlines

### ISSUE THREAD

**Issue by kettanaito** [oclif/oclif#707] opened 2021-11-03 14:26 UTC
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------

I'm reporting a bug.

What is the current behavior?
-----------------------------

### Steps to reproduce

1. Create a new `oclif` project.
2. Go to the `hello` command.
3. In the `run` method throw an error _with long message_:
```js
async run() {
  throw new Error('Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet')
}
```

4. See the error printed in `stderr` with unexpected newlines:
```sh
    Error: Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum·
        dolor sit amet Lorem ipsum dolor sit amet
```
> This is an exact `stderr`, including extra whitespace in the beginning of the line and the unexpected line break after `ipsum`.

What is the expected behavior?
------------------------------

When an error is thrown, its message formatting is preserved, even it's a long message string.

For the error above, I expect this to be written to `stderr`:

```sh
Error: Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet
```

This is also the formatting if you throw an error in Node.js. It'd be great to adhere to that. 

## Context

I'm testing that my command throws developer-friendly messages using automated tests with `Jest`. Due to the unexpected new lines in the error message, I cannot assert the message as it is.

**Comment by bboydflo** [comment] 2021-11-04 07:14
I am not sure this is related but it would be nice to be able to use a custom logger library.

**Comment by mdonnalley** [comment] 2024-03-01 19:17
Closing this since I can't reproduce it using the latest `@oclif/core` - please feel free to open a new issue in the oclif/core repository if you're still experiencing this.

```typescript
import {Command} from '@oclif/core'

export default class World extends Command {
  async run(): Promise<void> {
    throw new Error('Lorem ipsum dolor sit amet'.repeat(100))
  }
}
```

```
~/code/gh707 via ⬢ v20.11.0 
❯ bin/run.js hello world
    Error: Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet
```

**Closed by mdonnalley** 2024-03-01 19:17 UTC
