### ISSUE TITLE
Bug: registering ts-node multiple times

### ISSUE THREAD

**Issue by slavafomin** [oclif/oclif#333] opened 2020-03-10 19:30 UTC
Hello!

Thank you for this great tool!

However, right now it looks like Oclif is using `ts-node` under the hood and calls it's `register()` function multiple times (I believe once for each loaded plugin).

The thing is, that `ts-node` is not designed to be registered multiple times in a single Node virtual machine, which is [confirmed by it's author](https://github.com/TypeStrong/ts-node/issues/286#issuecomment-285137001).

As a custom CLI tool developer I want to have a full control of how `ts-node` is configured and whether it is used at all, because I want to load additional TypeScript configuration files on my own. Right now, Oclif, prevents me from doing this and creates a chaos in `ts-node` configuration, which leads to unpredictable behavior in runtime.

Therefore, I believe the following should be done:

1). `ts-node` support under the hood should be re-implemented to register only once.

2). The end developer should have full control of how `ts-node` is configured and used. There should be a way to disable it entirely. Actually, I would suggest to disable it by default in order to not cause unexpected behavior.

What do you think? Thanks!

**Comment by slavafomin** [comment] 2020-03-11 11:57
According to [the source code](https://github.com/oclif/config/blob/master/src/ts-node.ts#L49), the built-in use of `ts-node` could be disabled by using the `OCLIF_TS_NODE = 0` environment variable.

Here's how I use it right now in Node:

```js
process.env.OCLIF_TS_NODE = '0';

require('@oclif/command').run()
  .then(require('@oclif/command/flush'))
  .catch(require('@oclif/errors/handle'))
;
```

This helped me to resolve the issue on my side.

---

Also, it looks like `ts-node` has a special `scope` flag option, that actually allows to use multiple registrations, but it scopes them to the current working directory. Maybe it could fix this issue.

**Comment by slavafomin** [comment] 2020-03-11 12:02
Also, it looks like `ts-node` has a special [`scope` flag option](https://github.com/TypeStrong/ts-node#cli-and-programmatic-options), that actually allows to use multiple registrations, but it scopes them to the current working directory.

I've just tried to add `scope: true` to the `ts-node` [registration call](https://github.com/oclif/config/blob/master/src/ts-node.ts#L67-L70) in `src/ts-node.ts` and I can confirm that it fixes the conflicts. Looks like this one-line fix could actually remedy this issue.

**Comment by 0xdevalias** [comment] 2022-08-17 02:11
@mdonnalley It would be nice to include some context/description on why the issue is being closed (if it was completed, then when/where it was completed; if it's 'not planned' then more of an explanation of why it's not going to happen). This current process of 'close a huge pile of issues' with no context is generally considered pretty 'hostile'/'disrespectful' (for lack of a better term) to open source/collaboration/etc.

**Comment by mdonnalley** [comment] 2024-02-05 21:06
Closed by https://github.com/oclif/core/pull/759

**Closed by mdonnalley** 2024-02-05 21:06 UTC
Labels: bug, ESM
