### ISSUE TITLE
Use of `rm` command in npm scripts is not cross-platform

### ISSUE THREAD

**Issue by mattmazzola** [oclif/oclif#122] opened 2018-05-29 18:05 UTC
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Request a feature. The npm scripts should be cross-platform compatible. E.g. using `rimraf` instead of `rm` directly

What is the current behavior?
-----------------------------
steps to reproduce:
```
npx oclif multi test-01
cd test-01
npm run publish
```
This implicitly runs the prepack commands which use `rm` and fails because `rm` is not found.

What is the expected behavior?
------------------------------
npm scripts should run successfully after fresh new app with no modifications

```
    "@oclif/command": "1.4.30",
    "@oclif/config": "1.6.19",
    "@oclif/plugin-help": "1.2.11",
```

Windows 10 -  10.0.17134 Build 17134

**Comment by jdxcode** [comment] 2018-05-29 18:39
duplicate of https://github.com/oclif/oclif/issues/56

**Closed as completed by jdxcode** 2018-05-29 18:39 UTC
