### ISSUE TITLE
Generated command doesn't pass generated tests

### ISSUE THREAD

**Issue by muttonchop** [oclif/oclif#1263] opened 2024-01-22 17:12 UTC
*bug*/*help*
-----------------------------------------------------

What is the current behavior?
-----------------------------
I generated a new CLI with oclif in a monorepo that utilizes [npm workspaces](https://docs.npmjs.com/cli/v10/using-npm/workspaces), and everything was functional with the "hello, world" example provided with the initial generate. However, when I went to edit that initial "hello world" example I am no longer able to get the unittests to pass.

I assumed I had removed something important, and I created another command `oclif generate command mycmd2` to compare the differences, but this also fails its generated unittests with the same error even though the files appear to be the same: 

```
3) mycmd2
       runs mycmd2:
     Error: command mycmd2 not found
      at Config.runCommand (my-app\node_modules\@oclif\core\lib\config\config.js:387:19)
      at async Object.run (my-app\node_modules\@oclif\test\lib\command.js:21:28)
      at async Context.run (my-app\node_modules\fancy-test\lib\base.js:69:25)
```

Building and executing the command directly from the bin folder (.\bin\dev.cmd mycmd) produces the correct values.

project structure:

```
my-app/
├─ packages/
│  ├─ cli/
│  │  ├─ src/
│  │  │  ├─ commands/
│  │  │  │  ├─ mycmd.ts
│  │  │  │  ├─ mycmd2.ts
│  │  │  ├─ index.ts
│  │  ├─ test/
│  │  │  ├─ commands/
│  │  │  │  ├─ mycmd.test.ts
│  │  │  │  ├─ mycmd2.test.ts
│  ├─ otherPackage/
```

What is the expected behavior?
------------------------------
Unedited generate commands should execute successfully. 

npm version: 10.2.4
oclif version: 4.1.3

**Comment by mdonnalley** [comment] 2024-01-22 17:19
@muttonchop I'm not able to reproduce this on my end.

Do you, by chance, have an `oclif.manifest.json` present in your project? If that's there, then oclif is only going to find the commands that have been cached in that file

**Comment by muttonchop** [comment] 2024-01-22 17:30
I don't see it in my project. Would it be in a different place?

Did you create a npm workspace or just a regular project?

I was able to reproduce it with the following minimum setup:

```
mkdir oclif1263 && cd oclif1263
npm init -y
mkdir packages && cd packages
oclif generate .
```
root level package.json:
```
{
  "name": "oclif1263",
  "workspaces": [
    "packages/*"
  ]
}
```

**Comment by mdonnalley** [comment] 2024-01-22 18:12
@muttonchop Thanks for that! I believe this is the same issue as this one https://github.com/oclif/test/issues/390, which has already been placed on our backlog - so I'm going to close this one.

There's a yarn specific workaround in that issue (not sure if there's an npm equivalent you can use). You can also downgrade `@oclif/test` to 2.3.33 in the meantime.

We'd also welcome a PR if you'd like to get this fixed before we get to it on our backlog

**Closed by mdonnalley** 2024-01-22 18:12 UTC
