### ISSUE TITLE
Feature: non-dynamic discovery

### ISSUE THREAD

**Issue by pingu-codes** [oclif/oclif#899] opened 2022-06-04 00:17 UTC
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Feature

What is the current behavior?
-----------------------------
Commands are discovered at runtime via the package.json "commands" directory, this causes issues when attempting to package for distribution. Would it be possible to define commands at runtime to allow for packing?

**Comment by 0xdevalias** [comment] 2022-08-10 00:03
> this causes issues when attempting to package for distribution

@GodPingu Are you able to expand on what the specific issues are that you're running into when it comes to packing? And ideally how you feel that being able to define commands at runtime would help resolve the issues you're running into?

**Comment by mdonnalley** [comment] 2024-02-08 21:26
Duplicate of #653

**Closed by mdonnalley** 2024-02-08 21:26 UTC
